"""Academic item HTTP endpoints."""

from typing import Any
from uuid import UUID

from fastapi import APIRouter, Query, Response, status
from starlette.concurrency import run_in_threadpool

from app.modules.academic_items.application.handout_service import (
    handout_filename,
    render_handout_pdf,
)
from app.modules.academic_items.infrastructure.models import AcademicItem
from app.modules.academic_items.presentation.dependencies import (
    AcademicItemServiceDep,
)
from app.modules.academic_items.presentation.schemas import (
    AcademicItemCreate,
    AcademicItemResponse,
    AcademicItemSourceResponse,
    AcademicItemUpdate,
)
from app.modules.auth.presentation.dependencies import CurrentUser

router = APIRouter(prefix="/academic-items", tags=["academic-items"])


def _create_data(payload: AcademicItemCreate) -> dict[str, Any]:
    return {
        "module_id": payload.module_id,
        "item_category_id": payload.item_category_id,
        "title": payload.title,
        "description": payload.description,
        "content": payload.content,
        "item_metadata": (
            payload.metadata.model_dump(mode="json") if payload.metadata else None
        ),
    }


def _update_data(payload: AcademicItemUpdate) -> dict[str, Any]:
    fields = payload.model_dump(exclude_unset=True)
    data: dict[str, Any] = {}
    for key in ("module_id", "item_category_id", "title", "description", "content"):
        if key in fields:
            data[key] = getattr(payload, key)
    if "metadata" in fields:
        data["item_metadata"] = (
            payload.metadata.model_dump(mode="json") if payload.metadata else None
        )
    return data


def _without_heading(excerpt: str, section: str | None) -> str:
    if section and excerpt.startswith(section):
        return excerpt[len(section) :].strip()
    return excerpt


def _to_response(item: AcademicItem) -> AcademicItemResponse:
    return AcademicItemResponse(
        uuid=item.uuid,
        user_id=item.user_id,
        module_id=item.module_id,
        item_category_id=item.item_category_id,
        title=item.title,
        description=item.description,
        content=item.content,
        metadata=item.item_metadata,
        # Easy to forget, and its absence is invisible: the field has a default,
        # so leaving it out returns a valid response that quietly says "not
        # generated by AI" about every item. The page then cannot tell an item
        # still in the queue from one that has no material at all.
        generation_status=item.generation_status,
        created_by=item.created_by,
        created_at=item.created_at,
        updated_at=item.updated_at,
    )


@router.post(
    "", response_model=AcademicItemResponse, status_code=status.HTTP_201_CREATED
)
async def create_academic_item(
    payload: AcademicItemCreate,
    user: CurrentUser,
    service: AcademicItemServiceDep,
) -> AcademicItemResponse:
    """Create an academic item under a module owned by the user."""
    item = await service.create(user_id=user.uuid, data=_create_data(payload))
    return _to_response(item)


@router.get("", response_model=list[AcademicItemResponse])
async def list_academic_items(
    module_id: UUID,
    user: CurrentUser,
    service: AcademicItemServiceDep,
    limit: int = Query(default=50, ge=1, le=100),
    offset: int = Query(default=0, ge=0),
) -> list[AcademicItemResponse]:
    """List the academic items of a module owned by the user."""
    items = await service.list(
        user_id=user.uuid, module_id=module_id, limit=limit, offset=offset
    )
    return [_to_response(item) for item in items]


@router.get("/{item_id}", response_model=AcademicItemResponse)
async def get_academic_item(
    item_id: UUID, user: CurrentUser, service: AcademicItemServiceDep
) -> AcademicItemResponse:
    """Return a single academic item."""
    item = await service.get(user_id=user.uuid, item_id=item_id)
    return _to_response(item)


@router.get("/{item_id}/sources", response_model=list[AcademicItemSourceResponse])
async def get_academic_item_sources(
    item_id: UUID, user: CurrentUser, service: AcademicItemServiceDep
) -> list[AcademicItemSourceResponse]:
    """The passages the AI was given before it wrote this item.

    An empty list is a real answer and not a missing feature: it means the item
    was written with no document behind it, which is exactly what the reader
    needs to know before trusting a confident paragraph.
    """
    return [
        AcademicItemSourceResponse(
            rank=source.rank,
            document_id=source.document_id,
            document_title=title,
            section=source.section,
            # The stored excerpt is exactly what the model was shown, and the
            # chunker prefixes every passage with its breadcrumb. Sending both
            # would print the heading twice on a page that already shows it as
            # the label, so it comes off here, at the edge, and stays in the
            # database where it is evidence.
            excerpt=_without_heading(source.excerpt, source.section),
            # Cosine distance is what pgvector returns and similarity is what a
            # person can read. The conversion is exact, not a rescaling.
            similarity=None if source.distance is None else 1 - source.distance,
        )
        for source, title in await service.sources(user_id=user.uuid, item_id=item_id)
    ]


@router.get(
    "/{item_id}/handout.pdf",
    response_class=Response,
    responses={200: {"content": {"application/pdf": {}}}},
)
async def download_handout(
    item_id: UUID, user: CurrentUser, service: AcademicItemServiceDep
) -> Response:
    """The activity as a printable A4 PDF.

    Rendering happens per request rather than being stored: the material can be
    regenerated, and a cached file would quietly hand out the previous version.
    """
    context = await service.handout(user_id=user.uuid, item_id=item_id)
    pdf = await run_in_threadpool(render_handout_pdf, context)
    return Response(
        content=pdf,
        media_type="application/pdf",
        headers={
            "Content-Disposition": (
                f'attachment; filename="{handout_filename(context.title)}"'
            )
        },
    )


@router.patch("/{item_id}", response_model=AcademicItemResponse)
async def update_academic_item(
    item_id: UUID,
    payload: AcademicItemUpdate,
    user: CurrentUser,
    service: AcademicItemServiceDep,
) -> AcademicItemResponse:
    """Update an academic item."""
    item = await service.update(
        user_id=user.uuid, item_id=item_id, data=_update_data(payload)
    )
    return _to_response(item)


@router.delete("/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_academic_item(
    item_id: UUID, user: CurrentUser, service: AcademicItemServiceDep
) -> None:
    """Soft-delete an academic item."""
    await service.delete(user_id=user.uuid, item_id=item_id)
