"""Persistence for an academic item's figures.

Every read is filtered by owner here rather than in a caller: that is the
ownership invariant, and a figure is exactly the kind of row where forgetting it
would leak one teacher's material into another's handout.
"""

from uuid import UUID

from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.academic_items.infrastructure.models import AcademicItemFigure


class AcademicItemFigureRepository:
    """Reads and replaces the figures attached to an item."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def list_for_item(
        self, item_id: UUID, user_id: UUID
    ) -> list[AcademicItemFigure]:
        """This item's figures, in the order they appear in the content."""
        result = await self._session.execute(
            select(AcademicItemFigure)
            .where(
                AcademicItemFigure.academic_item_id == item_id,
                AcademicItemFigure.user_id == user_id,
            )
            .order_by(AcademicItemFigure.position)
        )
        return list(result.scalars())

    async def replace(self, item_id: UUID, figures: list[AcademicItemFigure]) -> None:
        """Swap this item's figures for a new set.

        Replace rather than append: an item is regenerated by re-running it, and
        the second run's illustrations are the item's illustrations, not an
        addition to the first run's.
        """
        await self._session.execute(
            delete(AcademicItemFigure).where(
                AcademicItemFigure.academic_item_id == item_id
            )
        )
        for figure in figures:
            self._session.add(figure)
        await self._session.flush()
