"""create document and chunk tables

Revision ID: 23b9bd6af1f0
Revises: 97faf01d0464
Create Date: 2026-07-04 22:30:48.913456

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b9bd6af1f0'
down_revision: str | None = '97faf01d0464'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_format',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_document_format'))
    )
    op.create_index(op.f('ix_document_format_format'), 'document_format', ['format'], unique=True)
    op.create_table('document',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('document_format_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_path', sa.String(length=1024), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_format_id'], ['document_format.uuid'], name=op.f('fk_document_document_format_id_document_format'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.uuid'], name=op.f('fk_document_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_document_format_id'), 'document', ['document_format_id'], unique=False)
    op.create_index(op.f('ix_document_subject_id'), 'document', ['subject_id'], unique=False)
    op.create_table('chunks',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('parser', sa.String(length=128), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.uuid'], name=op.f('fk_chunks_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_chunks'))
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_table('document_content',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('parser', sa.String(length=128), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.uuid'], name=op.f('fk_document_content_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_document_content'))
    )
    op.create_index(op.f('ix_document_content_document_id'), 'document_content', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_content_document_id'), table_name='document_content')
    op.drop_table('document_content')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_document_subject_id'), table_name='document')
    op.drop_index(op.f('ix_document_document_format_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_document_format_format'), table_name='document_format')
    op.drop_table('document_format')
    # ### end Alembic commands ###
