"""record what each model contributed to a run

A row per model per run rather than a column of JSON on the run: a dozen
activity workers finish at the same time and each adds its own model's share.
An upsert that adds is atomic; merging a document from Python is a
read-modify-write that loses most of them.

Note for whoever regenerates a migration here: autogenerate proposes dropping
``uq_users_email_active`` and creating a plain ``ix_users_email``. It is wrong.
That index is partial (``WHERE deleted_at IS NULL``) so a soft-deleted account
frees its address; a plain unique index would forbid ever reusing it. The
proposal was removed by hand, as in every migration before this.

Revision ID: 359ce9c315f4
Revises: a41c9e2b77d5
Create Date: 2026-08-16 14:49:09.651982

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359ce9c315f4'
down_revision: str | None = 'a41c9e2b77d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_generation_model_usage',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['plan_generation.uuid'], name=op.f('fk_plan_generation_model_usage_generation_id_plan_generation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_plan_generation_model_usage')),
    sa.UniqueConstraint('generation_id', 'model', name=op.f('uq_plan_generation_model_usage_generation_id'))
    )
    op.create_index(op.f('ix_plan_generation_model_usage_generation_id'), 'plan_generation_model_usage', ['generation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_generation_model_usage_generation_id'), table_name='plan_generation_model_usage')
    op.drop_table('plan_generation_model_usage')
    # ### end Alembic commands ###
