"""create academic_items table

Revision ID: 38fbd6dafdab
Revises: f6dfa676d25f
Create Date: 2026-07-04 17:40:39.836468

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38fbd6dafdab'
down_revision: str | None = 'f6dfa676d25f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_items',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('item_category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], name=op.f('fk_academic_items_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.uuid'], name=op.f('fk_academic_items_module_id_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name=op.f('fk_academic_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_academic_items'))
    )
    op.create_index(op.f('ix_academic_items_created_by'), 'academic_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_academic_items_item_category_id'), 'academic_items', ['item_category_id'], unique=False)
    op.create_index(op.f('ix_academic_items_module_id'), 'academic_items', ['module_id'], unique=False)
    op.create_index(op.f('ix_academic_items_user_id'), 'academic_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_items_user_id'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_module_id'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_item_category_id'), table_name='academic_items')
    op.drop_index(op.f('ix_academic_items_created_by'), table_name='academic_items')
    op.drop_table('academic_items')
    # ### end Alembic commands ###
