"""create plans table

Revision ID: 662ee933f319
Revises: 0b538c99f42a
Create Date: 2026-07-04 16:49:35.748902

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662ee933f319'
down_revision: str | None = '0b538c99f42a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.Date(), nullable=False),
    sa.Column('ends_at', sa.Date(), nullable=False),
    sa.Column('class_duration', sa.Integer(), nullable=False),
    sa.Column('class_per_week', sa.Integer(), nullable=False),
    sa.Column('total_weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('academic_items_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.uuid'], name=op.f('fk_plans_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name=op.f('fk_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_subject_id'), 'plans', ['subject_id'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_subject_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
