"""record which passages an item was written from

``chunk_id`` has deliberately no foreign key: it is a convenience pointer, and
a re-ingestion landing between retrieval and this insert must not fail an
activity over it.

The passage itself is copied into the row, not only referenced. Re-ingesting a
document replaces every one of its chunks, so a citation that was only a
foreign key would break exactly when somebody re-uploads a corrected file. What
is recorded is what was put in front of the model that day, which is the only
thing that can support or contradict what it then wrote.

Note for whoever regenerates a migration here: autogenerate proposes dropping
``uq_users_email_active`` and creating a plain ``ix_users_email``. It is wrong.
That index is partial (``WHERE deleted_at IS NULL``) so a soft-deleted account
frees its address; a plain unique index would forbid ever reusing it. The
proposal was removed by hand, as in every migration before this.

Revision ID: 917537b373e4
Revises: 92d818987519
Create Date: 2026-08-14 22:38:02.948151

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917537b373e4'
down_revision: str | None = '92d818987519'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_item_source',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('academic_item_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('section', sa.String(length=512), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_item_id'], ['academic_items.uuid'], name=op.f('fk_academic_item_source_academic_item_id_academic_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.uuid'], name=op.f('fk_academic_item_source_document_id_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_academic_item_source')),
    sa.UniqueConstraint('academic_item_id', 'rank', name=op.f('uq_academic_item_source_academic_item_id'))
    )
    op.create_index(op.f('ix_academic_item_source_document_id'), 'academic_item_source', ['document_id'], unique=False)
    op.create_index('ix_academic_item_source_item_rank', 'academic_item_source', ['academic_item_id', 'rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_academic_item_source_item_rank', table_name='academic_item_source')
    op.drop_index(op.f('ix_academic_item_source_document_id'), table_name='academic_item_source')
    op.drop_table('academic_item_source')
    # ### end Alembic commands ###
