"""create academic item category tables

Revision ID: 97faf01d0464
Revises: 38fbd6dafdab
Create Date: 2026-07-04 17:58:03.710707

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97faf01d0464'
down_revision: str | None = '38fbd6dafdab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_item_category',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_academic_item_category'))
    )
    op.create_table('academic_item_category_types',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('academic_item_category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['academic_item_category_id'], ['academic_item_category.uuid'], name=op.f('fk_academic_item_category_types_academic_item_category_id_academic_item_category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_academic_item_category_types'))
    )
    op.create_index(op.f('ix_academic_item_category_types_academic_item_category_id'), 'academic_item_category_types', ['academic_item_category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_item_category_types_academic_item_category_id'), table_name='academic_item_category_types')
    op.drop_table('academic_item_category_types')
    op.drop_table('academic_item_category')
    # ### end Alembic commands ###
