"""create modules table

Revision ID: f6dfa676d25f
Revises: 662ee933f319
Create Date: 2026-07-04 16:53:27.790028

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dfa676d25f'
down_revision: str | None = '662ee933f319'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.Date(), nullable=False),
    sa.Column('ends_at', sa.Date(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.uuid'], name=op.f('fk_modules_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.uuid'], name=op.f('fk_modules_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name=op.f('fk_modules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_modules'))
    )
    op.create_index(op.f('ix_modules_created_by'), 'modules', ['created_by'], unique=False)
    op.create_index(op.f('ix_modules_plan_id'), 'modules', ['plan_id'], unique=False)
    op.create_index(op.f('ix_modules_user_id'), 'modules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modules_user_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_plan_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_created_by'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
