"""Generation domain types."""

from enum import Enum


class GenerationRunStatus(str, Enum):
    """Lifecycle of a whole plan-generation run.

    PLANNING  -> the planner agent is producing the roadmap
    RUNNING   -> subtasks (academic items) are being generated by workers
    COMPLETED -> every subtask finished successfully
    PARTIAL   -> the run finished but some subtasks failed
    FAILED    -> the run could not even be planned / started
    """

    PLANNING = "planning"
    RUNNING = "running"
    COMPLETED = "completed"
    PARTIAL = "partial"
    FAILED = "failed"


class GenerationItemStatus(str, Enum):
    """Lifecycle of a single generated academic item (a subtask).

    Null on manually-created items; set only on AI-generated ones.
    """

    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
